name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.1.1
        with:
          required-ros-distributions: foxy
      - name: Create custom repos
        run: wget -O /tmp/all.repos https://github.com/MOCAP4ROS2-Project/mocap4ros2_vicon/blob/master/mocap4ros2.repos
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.1.0
        with:
          package-name: vicon2_driver
          target-ros2-distro: foxy
          vcs-repo-file-url: /tmp/all.repos
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml